"""empty message

Revision ID: 617bbd7acb95
Revises: 79af45391361
Create Date: 2022-04-04 22:38:57.938385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617bbd7acb95'
down_revision = '79af45391361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
