"""empty message

Revision ID: f2b50036ac5f
Revises: e4d0bdaba80b
Create Date: 2022-04-06 12:08:58.355327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b50036ac5f'
down_revision = 'e4d0bdaba80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    op.alter_column('post', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'tag', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('post', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    # ### end Alembic commands ###
